function header = generate_text_header(programName, what)
   DateTime = clock;
   [~, matVer] = strtok(version,'(');
   header = sprintf( '%s were generated by %s on %s at %02d:%02d:%02d by MATLAB %s.\n', what, programName, date, uint8( DateTime(4:6) ), matVer );
end