function write_compact_lifetime_dels_as_excel( sheetObj, progName, FileInfo, Fatigue, realFmt )
	
   % Set up the header.

   % Turn off warnings regarding adding sheets to the workbook.

   %warning off MATLAB:xlswrite:AddSheet

   globalOffset = [1 0];
   DateTime = clock;
   write_excel_cells( sheetObj, sprintf( 'These lifetime damage equivalent load estimates were generated by %s on %s at %02d:%02d:%02d.', progName, date, uint8( DateTime(4:6) ) ), globalOffset + [0 1] );
   globalOffset = globalOffset + [1 0];
   globalOffset = write_del_preamble_as_excel(globalOffset, progName, sheetObj, FileInfo, Fatigue);
             
   globalOffset = globalOffset + [2 0];      
      
   if (Fatigue.GoodmanFlag == 1 || Fatigue.GoodmanFlag == 2)
      if (Fatigue.DEL_Type == 1 || Fatigue.DEL_Type == 3 )
         globalOffset = write_compact_lifetime_del_table(1, globalOffset, sheetObj, FileInfo, Fatigue, realFmt);            
      end
      if (Fatigue.DEL_Type == 2 || Fatigue.DEL_Type == 3 )
         globalOffset = write_compact_lifetime_del_table(2, globalOffset, sheetObj, FileInfo, Fatigue, realFmt);       
      end
   end   
   
   if (Fatigue.GoodmanFlag == 0 || Fatigue.GoodmanFlag == 2)      
      write_compact_lifetime_del_table(3, globalOffset, sheetObj, FileInfo, Fatigue, realFmt);  
   end   
         

end