function write_compact_lifetime_damage_as_excel( sheetObj, progName, FileInfo, Fatigue, realFmt )
	
  
   % Set up the header.

   % Turn off warnings regarding adding sheets to the workbook.

   %warning off MATLAB:xlswrite:AddSheet


   DateTime = clock;

   globalOffset = [1 0];
   
   % Create table headers, etc.
   write_excel_cells( sheetObj, sprintf( 'These lifetime damage estimates were generated by %s on %s at %02d:%02d:%02d.', progName, date, uint8( DateTime(4:6) ) ), globalOffset + [0 1]);
   globalOffset = globalOffset + [1 0];
   globalOffset = write_lifetime_preamble_as_excel(globalOffset , progName, sheetObj, FileInfo, Fatigue, realFmt);
   
   globalOffset = globalOffset + [3 0];
         
   if (Fatigue.GoodmanFlag == 1 || Fatigue.GoodmanFlag == 2)
      globalOffset = write_compact_lifetime_damage_table(1, globalOffset, sheetObj, FileInfo, Fatigue, realFmt);        
      globalOffset = write_compact_lifetime_damage_table(2, globalOffset, sheetObj, FileInfo, Fatigue, realFmt);      
   end   
   
   if (Fatigue.GoodmanFlag == 0 || Fatigue.GoodmanFlag == 2)
      globalOffset = write_compact_lifetime_damage_table(3, globalOffset, sheetObj, FileInfo, Fatigue, realFmt);  
      write_compact_lifetime_damage_table(4, globalOffset, sheetObj, FileInfo, Fatigue, realFmt);
   end   

end